Repository Saikat-98/World-Covid-Tracker, pull requests merged in 2021-01, with the labels that each got.

#13 Added config file for Welcome BOT
  .github/config.yml
  README.md
  public/World-Covid-Tracker.gif
  public/World-Covid-Tracker.png
Labels: DWOC, Level-3

#12 updated issue #6
  public/manifest.json
Labels: DWOC, Level-5

#14 Fixed pics issue
  README.md
Labels: DWOC, Level-2

#17 Add Muthu Annamalai
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level-3

#19 added deployed app and changed title
  README.md
  public/index.html
Labels: DWOC, Level-2

#22 readme updated and list of contributors added
  README.md
  src/App.js
  src/Map.js
Labels: DWOC, level-1

#24 Add pull_request_template.md
  .github/pull_request_template.md
Labels: DWOC, Level-2

#23 image fixed
  DWoC.png
  README.md
Labels: DWOC, level-1

#26 updated issue template
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, level-1

#28 FIREBASE background color change
  README.md
Labels: DWOC, level-1
